### ISSUE TITLE
Support for jupyterlab

### ISSUE THREAD

**Issue by gioxc88** [widgetti/ipyaggrid#1]
Hello guys,
I just saw the deprecation warning on the old gitlab repo.
I wanted to ask what's the plan for this awesome project?
I have been trying for days to make it work in jupyterlab with zero luck so far.
Do you plan to fix the issue and realease a pip installable version?
Thanks

![image](https://user-images.githubusercontent.com/41852601/204387437-d9000162-2891-4309-bb1f-9593ddabe34f.png)

**Comment by vincent-grosbois** [comment]
Hello ! It's great that this repo is moving to a location where it's going to be maintained! 

As far as I know, we managed to make the project from JupyterLab work by applying the different pending PRs on the gitlab repo's head. But this is manual and requires to rebuild the npm packages etc.

But now I see that this repo is not on the same level as the one from gitlab, so I wonder which one is more up-to-date ?
IMHO there are 2 things to do at least:
1. update this repo so it's as current as the gitlab version, including the pending PRs
2. manage to take over the `ipyaggrid` pip package, so that it now points to this location and not to the gitlab repo

**Comment by gioxc88** [comment]
> Hello ! It's great that this repo is moving to a location where it's going to be maintained!
> 
> As far as I know, we managed to make the project from JupyterLab work by applying the different pending PRs on the gitlab repo's head. But this is manual and requires to rebuild the npm packages etc.
> 
> But now I see that this repo is not on the same level as the one from gitlab, so I wonder which one is more up-to-date ? IMHO there are 2 things to do at least:
> 
> 1. update this repo so it's as current as the gitlab version, including the pending PRs
> 2. manage to take over the `ipyaggrid` pip package, so that it now points to this location and not to the gitlab repo

Thanks for the answer.

1. After updating the current repo with the last PRs I think the most important thing to do is to make sure it works with JupyterLab without manual setup (only pip install) as this makes it very difficult for deployment and it's gonna limit the usability of the package.

I think I have tried every existing table widget so far and despite I wasn't able to test `ipyaggrid` (as it doesn't work for me) I am confident that this can become the "to go" widget for tables and forms in python. 
At the moment I think the "best" table widget is `ipydatagrid` but `ipyaggrig` far surpasses it in terms of functionalities and flexibility.

2.  On the doc there is still a link pointing to the old gitlab repo. It would be great if you could change it to github instead.

3. Finally after reading almost all the existing issues I think someone mentioned that there are specific versions of `jupyterlab/ipywidgets` that make the package work out of the box. I have tried some combination with no luck (always got the error in JupyterLab). For testing purposes, waiting for the next release that hopefully will fix all the issues) I think it would be awesome if someone could specify the exact versions of `jupyterlab/ipywidgets` that are compatible with the current version of `ipyaggrid` as this would be much easier than the manual installation (building the npm package)

Thank you and I look forward to use this incredible widget in my projects!

**Comment by vincent-grosbois** [comment]
hi @gioxc88 FYI those were just my suggestions for this newly-formed repo on github, I'm not a maintainer of it, in case this wasn't clear :D

**Comment by gioxc88** [comment]
> 

Yes it was clear :)

**Comment by gioxc88** [comment]
> hi @gioxc88 FYI those were just my suggestions for this newly-formed repo on github, I'm not a maintainer of it, in case this wasn't clear :D

Yes it was clear 😃

**Comment by vincent-grosbois** [comment]
> 1. After updating the current repo with the last PRs I think the most important thing to do is to make sure it works with JupyterLab without manual setup (only pip install) as this makes it very difficult for deployment and it's gonna limit the usability of the package.

If you want to just be able to say `pip install ipyaggrid` and have it link to this new repo, this will require PyPI ownership transfer, which may be a complex process.
If you want to be able to say `pip install https://github.com/widgetti/ipyaggrid/?` and have it install everything, I think this is simpler to do. Probably all there needs is that the npm generated files be versionned in the git tree as well. (But I'm not sure if it's considered bad practice or not)

**Comment by mariobuikhuizen** [comment]
We're in the process of transferring PyPI permissions.

I've moved the PR with the Jupyter Lab support to here (#8). The package is published to S3 by CI, which you can try with `pip install https://s3.us-west-2.amazonaws.com/widgetti.pub/ipyaggrid/8/merge/ipyaggrid-latest-py2.py3-none-any.whl`

**Comment by gioxc88** [comment]
> We're in the process of transferring PyPI permissions.
> 
> I've moved the PR with the Jupyter Lab support to here (#8). The package is published to S3 by CI, which you can try with `pip install https://s3.us-west-2.amazonaws.com/widgetti.pub/ipyaggrid/8/merge/ipyaggrid-latest-py2.py3-none-any.whl`

that is incredible! I can confirm it works for me!

**Comment by vincent-grosbois** [comment]
> We're in the process of transferring PyPI permissions.
Thanks ! I think you'll also need to transfer permissions for : https://npm.io/package/ipyaggrid

**Comment by vincent-grosbois** [comment]
> We're in the process of transferring PyPI permissions.
> 
> I've moved the PR with the Jupyter Lab support to here (#8). The package is published to S3 by CI, which you can try with `pip install https://s3.us-west-2.amazonaws.com/widgetti.pub/ipyaggrid/8/merge/ipyaggrid-latest-py2.py3-none-any.whl`
Hi !
It seems that having `latest` in the wheel name makes it a non-standard wheel name , would it be possible to put a version number , in that case it would pass the regexp? Right now some build tools are giving me `ValueError: invalid wheel name: 'ipyaggrid-latest-py2.py3-none-any.whl'`

**Comment by vincent-grosbois** [comment]
> We could use .post0 instead. Would that work for you?

sorry I don't know what this is :D

**Comment by mariobuikhuizen** [comment]
> If you want to name the wheel ipyaggrid-0.2.2.post0-py2.py3-none-any.whl I think it works 👍
Yeah, that's what I mean. I see I forgot to set the version number before .post0 😅

For reference: https://peps.python.org/pep-0440/#post-releases

**Comment by mariobuikhuizen** [comment]
Released in v0.3.0
