### ISSUE TITLE
Widget HTML export is broken

### ISSUE THREAD

**Issue by vincent-grosbois** [widgetti/ipyaggrid#10]
It seems that if I use the current code working in jupyterlab, the HTML export is broken (from jupyterlab)
Example:

```
from ipyaggrid import Grid
grid_options = {
    'columnDefs':[{'field':'x'}],
    'enableFilter':True,
    'enableSorting':True,
    'animateRows':True,
}

g = Grid(grid_options=grid_options,
         grid_data=[{'x':'1'}],
         paste_from_excel=True)
g
print(g.export_html(build=True))
```
--> save this to HTML and open it in browser

This results in an HTML page that doesn't load anything.
There are console errors that are in the console log:
```
require.min.js:1          GET file:///Users/XXXX/jupyterlab/ipyaggrid.js net::ERR_FILE_NOT_FOUND
embed-amd.js:26 Falling back to https://cdn.jsdelivr.net/npm/ for ipyaggrid@~0.2.2
embed-amd.js:16 TypeError: o._deserialize_state is not a function
    at xc._make_model (embed-amd.js:16:581882)
```

It's possible that the error is "just" that it's loading the old library from npm, which is broken. But I don't know what's the right way to fix this. I'm not sure if the good practice is to have the ipyaggrid.js as a file embeded in the widget or downloaded from npm, and also how the npm file is even generated

**Comment by mariobuikhuizen** [comment]
This is the same error I saw with ipywidgets8 in the classic notebook. I think this will be fixed when #12 is merged and released on npm.

**Comment by vincent-grosbois** [comment]
> This is the same error I saw with ipywidgets8 in the classic notebook. I think this will be fixed when #12 is merged and released on npm.

Hi ! I think the PR is merged but on https://npm.io/package/ipyaggrid i think it's still the old version.
Do you know how the update of the npm package work ? thanks !

**Comment by maartenbreddels** [comment]
https://www.npmjs.com/package/ipyaggrid shows 0.3.0

**Comment by vincent-grosbois** [comment]
> https://www.npmjs.com/package/ipyaggrid shows 0.3.0

wow my bad, I had an older version there. thanks !
I still need to recheck my example later to confirm that it works. I wonder if the current python code may be trying to load version 0.2.2 from npm and so would load the previous version

**Comment by mariobuikhuizen** [comment]
It was just released 😄 

yeah, I think you need to export it with v0.3.0 installed

**Comment by vincent-grosbois** [comment]
ah thank you ! 
I'd like to try, but now I'm not sure how I'm supposed to get the wheel for v0.3.0, or newer wheels when they are produced

**Comment by mariobuikhuizen** [comment]
With `pip install "ipyaggrid>=0.3.0"`.
Then do the export again and the exported widget should work.

**Comment by vincent-grosbois** [comment]
ah thanks, I missed the fact that the repo is back on pypi ;) perfect then, I'll have a look later

**Comment by vincent-grosbois** [comment]
I retried the steps in first message on a clean install with 0.3.0, and the HTML export works ! 
thanks a lot, you can close the issue
