### ISSUE TITLE
widget HTML exported file can't be opened in jupyterlab

### ISSUE THREAD

**Issue by vincent-grosbois** [widgetti/ipyaggrid#17]
Hello

It seems there are still issues with the HTML export
Specifically, if I now follow the steps in #10 , I'm able to generate a HTML file that works as standalone, it's great ! (file attached below)

However, if I try to open the open the HTML from the jupyter lab HTML viewer, it fails... Note that the jupyterlab instance is the one that produced the HTML file initially, so it terms of versions etc this is the same.

When I try to open the HTML file in jupyterlab (with the "trust HTML" on), I get the following error in the console:
```
embed-amd.js:26 Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at embed-amd.js:26:37945
    at Object.<anonymous> (embed-amd.js:26:41241)
    at Object.execCb (require.min.js:1:12861)
    at b.check (require.min.js:1:6615)
    at b.enable (require.min.js:1:9363)
    at Object.enable (require.min.js:1:11918)
    at b.<anonymous> (require.min.js:1:9220)
    at require.min.js:1:814
    at each (require.min.js:1:289)
    at b.enable (require.min.js:1:8720)
(anonymous) @ embed-amd.js:26
(anonymous) @ embed-amd.js:26
execCb @ require.min.js:1
check @ require.min.js:1
enable @ require.min.js:1
enable @ require.min.js:1
(anonymous) @ require.min.js:1
(anonymous) @ require.min.js:1
each @ require.min.js:1
enable @ require.min.js:1
init @ require.min.js:1
(anonymous) @ require.min.js:1
setTimeout (async)
req.nextTick @ require.min.js:1
o @ require.min.js:1
requirejs @ require.min.js:1
(anonymous) @ embed-amd.js:29
(anonymous) @ embed-amd.js:29
DevTools failed to load source map: Could not load content for https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd-render.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

Can someone help me understand the following:
- is it an issue in ipyaggrid or in the ipywidget system ?
- is it normal that the https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd-render.js.map yields a 404 error ?
- What is being done differently when I open the file directly on my browser, for it to work ?

thanks!

[x.html.gz](https://github.com/widgetti/ipyaggrid/files/10207877/x.html.gz)

**Comment by vincent-grosbois** [comment]
it seems this could be an issue with ipywidget itself and the way it works in iframe.
I've opened an issue here: https://github.com/jupyter-widgets/ipywidgets/issues/3652

**Comment by mariobuikhuizen** [comment]
Please feel free to reopen if it turns out not to be an ipywidget/jupyter issue.
