### ISSUE TITLE
Add ipyaggrid to conda forge

### ISSUE THREAD

**Issue by LeoCo** [widgetti/ipyaggrid#19]
Hello

I'd like to add ipyaggrid to conda forge so we can install it via conda, I'm happy to take care of the process https://conda-forge.org/docs/maintainer/adding_pkgs.html#

Currently I'm blocked because we are missing the source contribution files in pypi https://pypi.org/project/ipyaggrid/0.3.1/#files and I can't use graykull

I've created a PR to fix it, once merged I can create the conda recipe. Could you please have a look? Thanks!

**Comment by mariobuikhuizen** [comment]
The source distribution is now available: https://pypi.org/project/ipyaggrid/0.3.2/#files

**Comment by LeoCo** [comment]
ipyaggrid has been added to conda-forge 🎉
https://anaconda.org/conda-forge/ipyaggrid
https://github.com/conda-forge/ipyaggrid-feedstock

**Comment by maartenbreddels** [comment]
Nice, thanks you!
