### ISSUE TITLE
TypeError: o._deserialize_state is not a function

### ISSUE THREAD

**Issue by teraStars** [widgetti/ipyaggrid#20]
Python 3.9.16
Jupyter Notebook 6.5.2
ipywidgets 8.0.4
ipyaggrid 0.3.2

When i run my cell ,it throw errors:
[Open Browser Console for more detailed log - Double click to close this message]
Model class 'AgGridModel' from module 'ipyaggrid' is loaded but can not be instantiated
TypeError: o._deserialize_state is not a function
    at u._make_model (http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js?v=20230219013016:2:747339)

The notebook have worked well for 2 years,but after i update my conda,then it broke.

**Comment by teraStars** [comment]
I have resolved it.
Reinstall ipywidgets ,and refresh the chrome page,then it fixed.

**Comment by maartenbreddels** [comment]
Good to hear you solved it!
