### ISSUE TITLE
height = 100%

### ISSUE THREAD

**Issue by gioxc88** [widgetti/ipyaggrid#33]
is it possible to figure make the grid full height?
I couldn't find anything in the doc 

Thanks

**Comment by mariobuikhuizen** [comment]
Full height of what? Can you provide a bit more context?

**Comment by mariobuikhuizen** [comment]
Thanks for the clarification!

`'domLayout': 'autoHeight'` seems to work in `grid_options`. The height is then still limited by the default height, which can be fixed by setting `grid.height` to `-1`.

Example:
```python
import json
import urllib.request as ur
from ipyaggrid import Grid

url = "https://www.ag-grid.com/example-assets/olympic-winners.json"
with ur.urlopen(url) as res:
    data = json.loads(res.read().decode("utf-8"))

columnDefs = [
    {"headerName": "Country", "field": "country"},
    {"headerName": "Year", "field": "year"},
    {"headerName": "Sport", "field": "sport"},
    {"headerName": "Athlete", "field": "athlete"},
    {"headerName": "Gold", "field": "gold"},
]


gridOptions = {
    "enableColResize": True,
    "columnDefs": columnDefs,
    "enableSorting": True,
    "defaultColDef": {"sortable": True},
    "domLayout": "autoHeight",
}

grid1 = Grid(quick_filter=True,
             theme="ag-theme-balham",
             compress_data=True,
             grid_options=gridOptions,
             grid_data=data,
             columns_fit="auto",
             height=-1)
grid1
```

**Comment by mariobuikhuizen** [comment]
It's an ipyaggrid thing. Where the height is an int with 350 as default. Setting it to -1 so no height is set is a bit of a hack actually.

**Comment by gioxc88** [comment]
That works thanks a lot.
The only problem I see is that when you use the `agSetColumnFilter` and  uncheck `Select all` it shrinks, making it difficult to operate

**Comment by mariobuikhuizen** [comment]
I see. We may need to add more style options (e.g. min-height ).

A workaround would be to use the`css_rules` of `Grid`:
```python
Grid(css_rules="""
                .ag-root-wrapper .ag-layout-auto-height {
                    min-height: 200px;
                }
             """,
       ...
```

**Comment by mariobuikhuizen** [comment]
Closing this as answered.
