### ISSUE TITLE
Cannot edit the table using responsive setting 

### ISSUE THREAD

**Issue by hhlim333** [widgetti/ipyaggrid#49]
Hi,

I have tried to use the ipyaggrid to turn a dataframe to a editable table.

It work perfect in voila or jupyter notebook.

However, it does not work when I try to set a responsive setting.

A responsive setting like a mobile setting or Ipad setting ( https://developer.chrome.com/docs/devtools/device-mode/).

I cannot edit the table value when I use Google DevTools

Thank you

**Comment by mariobuikhuizen** [comment]
Thanks for reporting this issue, however, I can't reproduce this issue. It works for me in DevTools mobile view:

https://github.com/widgetti/ipyaggrid/assets/46192475/46e04de6-1488-425a-909b-d01547f9ef3d
