### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by vthemelis** [widgetti/ipyaggrid#50]
Can we release the latest changes?

Let me know if this is something I could trigger myself.

**Comment by vthemelis** [comment]
@mariobuikhuizen could you trigger this? It's to pick up the bugfix from yesterday

**Comment by mariobuikhuizen** [comment]
It's released as 0.5.0. But when I test it in a new environment, I don't see the `<NA>` when I run it in a notebook.  Can you try if it works for you?

**Comment by vthemelis** [comment]
Just tried it with
```Python
import pandas as pd

df = pd.DataFrame({"a": [pd.NA]})
```

and it works for me (ie it prints `<NA>` as the sole value in the table).

Thanks!

**Comment by mariobuikhuizen** [comment]
Turns out I used pandas 2 in the new environment, which turns `pd.NA` into `None` in it's `.to_dict()` function.
