### ISSUE TITLE
does it support jupyterlab4？

### ISSUE THREAD

**Issue by linlol** [widgetti/ipyaggrid#69]
Hi all, we are using ipyaggrid and planning to support jupyter lab 4, I wonder that does the latest version support jupyter lab 4?

If not, I would try to make it work internally and raise pr (maybe around this summer?

**Comment by linlol** [comment]
Looks like it is out of maintainence and I make compatible version in our internal fork.

Feel free to let me know if you also need it, I would briefly share you what I did (it would take around one day if you are familiar with Jupyter/Ipywidget lifecycle)

**Comment by maartenbreddels** [comment]
Hi,

yes, it is (or should!) be compatible with jupyter lab 4. And we are maintaining ipyaggrid. 

Regards,

Maarten

**Comment by linlol** [comment]
Hi @maartenbreddels, thanks a lot for your kind reply!

https://github.com/widgetti/ipyaggrid/blob/master/pyproject.toml#L2 as defined here... it would not support jlab 4 at least for the toml change. (And if I remember correctly, we might need a few more things after change pyproject.toml due to some incompatiblility from ipywidgets or something else... sorry that I forget the detail)

On my side, actually I created a minimal extension and paste the logic code (make it consistent with the latest Jupyter extension pattern).

If you or @mariobuikhuizen are happy to make it Jlab4-compatible, I am happy to check if we can make it compatible with minimal change (the change I made internally was too large, changed folder structure, refactor python setup from setup.py to pyproject.toml, which is not good for open source project)

**Comment by maartenbreddels** [comment]
Hi,

that is only for the build environment and is not directly related to the runtime constraints. Did you try to use it with jupyter lab 4? As far as I know, it works in Jupyter lab 4.

Regards,

Maarten

**Comment by linlol** [comment]
> Hi,
> 
> that is only for the build environment and is not directly related to the runtime constraints. Did you try to use it with jupyter lab 4? As far as I know, it works in Jupyter lab 4.
> 
> Regards,
> 
> Maarten

hmmmm sounds a bit tricky as I tried it (and failed)

Please give me a few time let me try to create a neat venv with jupyter 4 and ipyaggrid only

Thanks a lot for your kind message!

**Comment by linlol** [comment]
had a further look today, I am sorry that I was wrong last time. Yes it is jupyter 4 compatible.

I am working on a complicate environment, probably something else breaks ipyaggrid.

**Comment by maartenbreddels** [comment]
Good to hear, and thank you for reporting back to us.

Regards,

Maarten
